---
     - name: initialize master
       command: kubeadm init --pod-network-cidr=10.240.0.0/16 --ignore-preflight-errors=NumCPU --ignore-preflight-errors=Mem
       register: kubeadm_init
       args:
         creates: /etc/kubernetes/admin.conf
     
     - name: Configure kubectl
       shell: |
        mkdir -p $HOME/.kube
        cp -i /etc/kubernetes/admin.conf $HOME/.kube/config
        chown $(id -u):$(id -g) $HOME/.kube/config
    
     - name: kubeadm join command
       command: kubeadm token create --print-join-command
       register: join_command

     - name: Save the join command
       set_fact:
         join_cmd: "{{join_command.stdout}}" 
