apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: webserver
  name: webserver
  namespace: default
spec:
  replicas: 3
  selector:
    matchLabels:
      app: mailserver
  template:
    metadata:
      labels:
        app: webserver
    spec:
      containers:
      - image: yagya123/mailserver
        name: mailserver
