apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: "2025-08-29T16:55:34Z"
  generation: 1
  labels:
    app: webserver
  name: webserver
  namespace: default
  resourceVersion: "125348"
  uid: 97e0f664-7b21-4364-9738-7260de81bc53
spec:
  progressDeadlineSeconds: 600
  replicas: 3
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: webserver
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: webserver
    spec:
      containers:
      - image: yagya123/searchserver
        imagePullPolicy: Always
        name: searchserver
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
status: {}
