apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: "2025-08-29T12:54:16Z"
  generation: 1
  labels:
    app: webserver
  name: webserver
  namespace: default
  resourceVersion: "97106"
  uid: 02643567-c3ba-4228-a9cd-a81633351ed8
spec:
  progressDeadlineSeconds: 600
  replicas: 2
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: webserver
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: webserver
    spec:
      containers:
      - image: yagya123/searchserver
        imagePullPolicy: Always
        name: searchserver
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
status: {}
