apiVersion: v1
kind: Service
metadata:
  creationTimestamp: "2025-08-30T12:33:42Z"
  labels:
    app: webserver
  name: webserver
  namespace: default
  resourceVersion: "138816"
  uid: c849c78e-46ea-42de-97f2-12c8c92b8c52
spec:
  clusterIP: 10.101.117.69
  clusterIPs:
  - 10.101.117.69
  externalTrafficPolicy: Cluster
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - nodePort: 31619
    port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: webserver
  sessionAffinity: None
  type: NodePort
status:
  loadBalancer: {}
