---
 - name: Initialize token to join worker
   hosts: masters
   become: true
   tasks:
     - name: kubeadm join command
       command: kubeadm token create --print-join-command
       register: join_command

     - name: Save the join command
       set_fact:
         join_cmd: "{{join_command.stdout}}"

 - name: Join workers to cluster
   hosts: worker
   become: true
   tasks:
     - name: Join workers
       command: "{{hostvars[groups['masters'][0]].join_cmd }}"
  
            

